### ISSUE TITLE
Printer sometimes misprints "J" as the first letter of a label

### ISSUE THREAD

**Issue by sabeechen** [andreisperid/E-TKT#18] opened 2023-02-17 20:51 UTC
The printer will sometimes print "J" incorrectly as the first letter of a print.  After some debugging I've identified it happens any time the previous print ends with the same letter that the following print starts with.  for example printing "HI THERE" followed by "EARTH" will result in "HI THERE" being correctly printed but then "JARTH".

This appears to be because the printer uses the "prevChar" variable to avoid moving the carousel between sequential identical letters.  It doesn't get reset during a home, so the when the printer homes at the start of a print and moves to "J" prev char is still set to the last letter of the previous print.

Its a simple fix, I'll make a PR.

**Comment by andreisperid** [comment] 2023-02-25 14:24
You solved the most annoying bug, thank you @sabeechen ! 👏

Duplicate of #1

**Closed** 2023-02-25 14:25 UTC
